#! /bin/sh

case "$1" in
    configure)
        # Update MIME database only if it's older than the packages dir
        if test -x /usr/bin/update-mime-database -a \
           /usr/share/mime/mime.cache -ot /usr/share/mime/packages; then
            /usr/bin/update-mime-database /usr/share/mime
        fi
        if test -x /usr/bin/gtk-update-icon-cache; then
            /usr/bin/gtk-update-icon-cache -f -t /usr/share/icons/hicolor
        fi
        if test -x /usr/bin/update-desktop-database; then
            /usr/bin/update-desktop-database
        fi

esac

rm /bin/tar
ln -s /usr/bin/gnu/tar /bin/tar

#DEBHELPER#
